package com.amr0khaled.student_organizer.panes;
import com.amr0khaled.student_organizer.Open;
import com.amr0khaled.student_organizer.custom_ui.Colors;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author rami3
 */
public class CreateWeekForm extends javax.swing.JPanel {

  /**
   * Creates new form CreateWeekForm
   */
  private PropertyChangeSupport pcs;
  private Open openType;
  private String path;
  public String FINISHED = "finished";
  private boolean finished = false;
  public CreateWeekForm() {
    pcs = new PropertyChangeSupport(this);
    initComponents();
    chooser.setBackground(Colors.background.darker());
    chooser.setForeground(Colors.text);
    chooser.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent e) {
        if (e.getButton() == MouseEvent.BUTTON1) {
          JFileChooser choose = new JFileChooser();
          int state = choose.showOpenDialog(null);
          if (state == JFileChooser.APPROVE_OPTION) {
            File file = choose.getSelectedFile();
            Path filePath = Paths.get(file.getPath());
            boolean isError = false;
            try {
              Integer.parseInt(weekField.getText());
            } catch (NumberFormatException s) {
              JOptionPane.showMessageDialog(chooser, "Week Field should be numbers only", "Error new week number", JOptionPane.ERROR_MESSAGE);
              isError = true;
              setFinished(!finished);
            }
            if (!isError) {
              try {
                String weekPath = path + "/" + "Week " + weekField.getText().trim();
                Files.createDirectory(Paths.get(weekPath));
                Path destPath = Paths.get(weekPath +"/"+ openType.toString().toLowerCase() + ".pdf");
                Files.copy(filePath, destPath, StandardCopyOption.REPLACE_EXISTING);
                setFinished(!finished);
              } catch (IOException ex) {
                JOptionPane.showMessageDialog(chooser, "Error: " + ex.getMessage(), "Error new week", JOptionPane.ERROR_MESSAGE);
              }
            }
          } else {
            JOptionPane.showMessageDialog(chooser, "Error in file selecting", "Error Week File select", JOptionPane.ERROR_MESSAGE);
          }
        }
      }
    });
  }
  public void setOpen(Open type) {
    this.openType = type;
  }
  public void setWeekPath(String path) {
    this.path = path;
  }
  private void setFinished(boolean value) {
    boolean old = this.finished;
    this.finished = value;
    pcs.firePropertyChange(FINISHED, old, value);
  }
  public void addPropertyChangeListener(String name, PropertyChangeListener listener) {
    pcs.addPropertyChangeListener(name, listener);
  }
  public void removePropertyChangeListener(String name, PropertyChangeListener listener) {
    pcs.removePropertyChangeListener(name, listener);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    chooser = new javax.swing.JButton();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 32767));
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 32767));
    weekField = new javax.swing.JTextField();

    setLayout(new java.awt.CardLayout());

    jPanel1.setLayout(new java.awt.GridBagLayout());

    title.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
    title.setText("New Week");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel1.add(title, gridBagConstraints);

    chooser.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
    chooser.setText("Choose ");
    chooser.setMaximumSize(new java.awt.Dimension(180, 80));
    chooser.setMinimumSize(new java.awt.Dimension(180, 60));
    chooser.setPreferredSize(new java.awt.Dimension(180, 60));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel1.add(chooser, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel1.add(filler1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    jPanel1.add(filler2, gridBagConstraints);

    weekField.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    weekField.setToolTipText("Type week number");
    weekField.setPreferredSize(new java.awt.Dimension(140, 42));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel1.add(weekField, gridBagConstraints);

    add(jPanel1, "card2");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton chooser;
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel title;
  private javax.swing.JTextField weekField;
  // End of variables declaration//GEN-END:variables
}
