/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.amr0khaled.student_organizer.panes;
import com.amr0khaled.student_organizer.Open;
import com.amr0khaled.student_organizer.custom_ui.Colors;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rami3
 */
public class CreateSubjectForm extends javax.swing.JPanel {

  /**
   * Creates new form CreateSubjectForm
   */
  private PropertyChangeSupport pcs;
  private String path;
  private Open openType;
  public String FINISHED = "finished_new_subject";
  private boolean finished = false;
  public String dir = null;
  public String subjectTitle = null;
  public CreateSubjectForm() {
    pcs = new PropertyChangeSupport(this);
    initComponents();
    newSubject.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent e) {
        if (e.getButton() == MouseEvent.BUTTON1) {
          String text = textField.getText();
          if (text.length() == 0) {
            JOptionPane.showMessageDialog(newSubject, "Subject Name Field should be filled", "Error Subject Name", JOptionPane.ERROR_MESSAGE);
          } else {
            try {
              File file = new File(path + "/" + text);
              file.mkdir();
              subjectTitle = text;
              dir = file.getPath();
            } catch(Exception ex) {
              System.out.println(".");
            }
            setFinished(!finished);
          }
        }
      }
    });
  }
  public void setOpen(Open type) {
    this.openType = type;
  }
  public void setSubjectPath(String path) {
    this.path = path;
  }
  private void setFinished(boolean value) {
    boolean old = this.finished;
    this.finished = value;
    pcs.firePropertyChange(FINISHED, old, value);
  }
  public void addPropertyChangeListener(String name, PropertyChangeListener listener) {
    pcs.addPropertyChangeListener(name, listener);
  }
  public void removePropertyChangeListener(String name, PropertyChangeListener listener) {
    pcs.removePropertyChangeListener(name, listener);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    textField = new javax.swing.JTextField();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 32767));
    newSubject = new javax.swing.JButton();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 32767));

    setLayout(new java.awt.CardLayout());

    jPanel1.setLayout(new java.awt.GridBagLayout());

    title.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
    title.setText("New Subject");
    jPanel1.add(title, new java.awt.GridBagConstraints());

    textField.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    textField.setToolTipText("Type your subject name");
    textField.setMinimumSize(new java.awt.Dimension(240, 40));
    textField.setPreferredSize(new java.awt.Dimension(300, 40));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel1.add(textField, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel1.add(filler2, gridBagConstraints);

    newSubject.setBackground(Colors.background.darker());
    newSubject.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
    newSubject.setForeground(Colors.text);
    newSubject.setText("New");
    newSubject.setToolTipText("Type to create new subject");
    newSubject.setMaximumSize(new java.awt.Dimension(180, 80));
    newSubject.setMinimumSize(new java.awt.Dimension(180, 60));
    newSubject.setPreferredSize(new java.awt.Dimension(180, 60));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel1.add(newSubject, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    jPanel1.add(filler1, gridBagConstraints);

    add(jPanel1, "card3");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton newSubject;
  private javax.swing.JTextField textField;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
