/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.amr0khaled.student_organizer.panes;
import com.amr0khaled.student_organizer.Open;
import com.amr0khaled.student_organizer.Subject;
import com.amr0khaled.student_organizer.controller.SubjectController;
import com.amr0khaled.student_organizer.custom_ui.Colors;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Optional;

/**
 *
 * @author rami3
 */
public class DashboardPanel extends javax.swing.JPanel {

  /**
   * Creates new form DashboardPanel
   */
  private SubjectsContainer subcontainer;
  private SubjectsContainer seccontainer;
  private SubjectsContainer assicontainer;
  private ArrayList<Subject> subs = new ArrayList<Subject>();
  private static File path;
  public static DashboardPanel instance = new DashboardPanel();
  private boolean listener = false;
  public DashboardPanel() {
    initComponents();
  }
  public static DashboardPanel getInstance() {
    return instance;
  }
  public File getPath() {
    return path;
  }
  public void setPath(File path) {
    this.path = path;
  }
  public void refresh() {
    mainPanel.removeAll();
    mainPanel.revalidate();
    SubjectController.getInstance().refresh();
    subs = SubjectController.getInstance().getSubjects();
    System.out.println("size" + subs.size());
    subcontainer = new SubjectsContainer(Optional.ofNullable(checkAndGet(Open.Lecture)), path, Open.Lecture);
    seccontainer = new SubjectsContainer(Optional.ofNullable(checkAndGet(Open.Section)), path, Open.Section);
    assicontainer = new SubjectsContainer(Optional.ofNullable(checkAndGet(Open.Assignment)), path, Open.Assignment);
    settings.setVisible(false);
    changeBackgroundColor("lectures");
    mainPanel.add(subcontainer);
    if (!listener) {
      addListeners();
    }
    mainPanel.repaint();
  }
  private void addListeners() {
    lectures.addMouseListener(new MouseAdapter() {
      @Override
      public void mousePressed(MouseEvent e) {
        if (e.getButton() == 1) {
          changeBackgroundColor("lectures");
          mainPanel.removeAll();
          mainPanel.add(subcontainer);
          mainPanel.revalidate();
          mainPanel.repaint();
        }
      }
    });
    sections.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        if (e.getButton() == 1) {
          changeBackgroundColor("sections");
          mainPanel.removeAll();
          mainPanel.add(seccontainer);
          mainPanel.revalidate();
          mainPanel.repaint();
        }
      }
    });
    assignments.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        if (e.getButton() == 1) {
          changeBackgroundColor("assignments");
          mainPanel.removeAll();
          mainPanel.add(assicontainer);
          mainPanel.revalidate();
          mainPanel.repaint();
        }
      }
    });
    listener = true;
  }
  private boolean exists(Open open) {
    for (Subject sub: this.subs) {
      sub.setOpen(open);
      if (sub.exists()) {
        return true;
      }
    }
    return false;
  }
  private ArrayList<Subject> checkAndGet(Open open) {
    if (exists(open)) {
      return subs;
    }
    return null;
  }
  Color openedColor = new Color((float)0.0, (float)0.0, (float)0.0, (float)0.1);
  Color closedColor = new Color(0, 0, 0, 0);

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jFrame1 = new javax.swing.JFrame();
    jFrame2 = new javax.swing.JFrame();
    jFrame3 = new javax.swing.JFrame();
    jFrame4 = new javax.swing.JFrame();
    header = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    studentGrade = new javax.swing.JPanel();
    studentName = new javax.swing.JLabel();
    semester = new javax.swing.JLabel();
    year = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    mainPanel = new javax.swing.JPanel();
    sideBar = new javax.swing.JPanel();
    sideItems = new javax.swing.JPanel();
    sections = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    assignments = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    lectures = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    settings = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

    javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
    jFrame1.getContentPane().setLayout(jFrame1Layout);
    jFrame1Layout.setHorizontalGroup(
      jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jFrame1Layout.setVerticalGroup(
      jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
    jFrame2.getContentPane().setLayout(jFrame2Layout);
    jFrame2Layout.setHorizontalGroup(
      jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jFrame2Layout.setVerticalGroup(
      jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
    jFrame3.getContentPane().setLayout(jFrame3Layout);
    jFrame3Layout.setHorizontalGroup(
      jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jFrame3Layout.setVerticalGroup(
      jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
    jFrame4.getContentPane().setLayout(jFrame4Layout);
    jFrame4Layout.setHorizontalGroup(
      jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jFrame4Layout.setVerticalGroup(
      jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    setForeground(Colors.text);
    setMaximumSize(new java.awt.Dimension(1920, 1080));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setName("Student Organizer"); // NOI18N

    header.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    header.setMaximumSize(new java.awt.Dimension(1920, 96));
    header.setMinimumSize(new java.awt.Dimension(1280, 96));
    header.setPreferredSize(new java.awt.Dimension(1280, 96));

    title.setFont(new java.awt.Font("Poppins Light", 0, 28)); // NOI18N
    title.setForeground(Colors.text);
    title.setText("Student Material Organizer");

    javax.swing.GroupLayout studentGradeLayout = new javax.swing.GroupLayout(studentGrade);
    studentGrade.setLayout(studentGradeLayout);
    studentGradeLayout.setHorizontalGroup(
      studentGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 362, Short.MAX_VALUE)
    );
    studentGradeLayout.setVerticalGroup(
      studentGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 37, Short.MAX_VALUE)
    );

    studentName.setFont(new java.awt.Font("Poppins Light", 0, 20)); // NOI18N
    studentName.setText("Amr");

    semester.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
    semester.setText("Last Semester");

    year.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
    year.setText("2nd Year");

    javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
    header.setLayout(headerLayout);
    headerLayout.setHorizontalGroup(
      headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(headerLayout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(title)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
        .addComponent(studentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(year)
        .addGap(24, 24, 24)
        .addComponent(semester)
        .addGap(18, 18, 18)
        .addComponent(studentName)
        .addGap(24, 24, 24))
    );
    headerLayout.setVerticalGroup(
      headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(headerLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(year)
            .addComponent(semester)
            .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(title)
          .addComponent(studentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(27, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(10, 9, 8));
    jPanel2.setMaximumSize(new java.awt.Dimension(2, 32767));
    jPanel2.setMinimumSize(new java.awt.Dimension(2, 300));
    jPanel2.setPreferredSize(new java.awt.Dimension(2, 10));
    jPanel2.setLayout(new java.awt.CardLayout());

    mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    mainPanel.setMinimumSize(new java.awt.Dimension(1043, 624));
    mainPanel.setPreferredSize(new java.awt.Dimension(1043, 624));
    mainPanel.setLayout(new java.awt.CardLayout());

    sideBar.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    sideBar.setMaximumSize(new java.awt.Dimension(235, 12345));
    sideBar.setMinimumSize(new java.awt.Dimension(235, 500));
    sideBar.setPreferredSize(new java.awt.Dimension(235, 235));
    sideBar.setLayout(new java.awt.GridBagLayout());

    sections.setBackground(closedColor);
    sections.setMaximumSize(new java.awt.Dimension(235, 64));
    sections.setMinimumSize(new java.awt.Dimension(235, 64));
    sections.setPreferredSize(new java.awt.Dimension(235, 64));

    jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 28)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Sections");
    jLabel5.setPreferredSize(new java.awt.Dimension(119, 64));
    sections.add(jLabel5);

    assignments.setBackground(closedColor);
    assignments.setMaximumSize(new java.awt.Dimension(235, 64));
    assignments.setMinimumSize(new java.awt.Dimension(235, 64));
    assignments.setPreferredSize(new java.awt.Dimension(235, 64));
    assignments.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        assignmentsMouseClicked(evt);
      }
    });

    jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 28)); // NOI18N
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Assignments");
    assignments.add(jLabel6);

    lectures.setBackground(closedColor);
    lectures.setMaximumSize(new java.awt.Dimension(235, 64));
    lectures.setMinimumSize(new java.awt.Dimension(235, 64));
    lectures.setPreferredSize(new java.awt.Dimension(235, 64));

    jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 28)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("Lectures");
    jLabel7.setAlignmentY(0.0F);
    jLabel7.setMaximumSize(new java.awt.Dimension(117, 64));
    jLabel7.setMinimumSize(new java.awt.Dimension(117, 64));
    jLabel7.setPreferredSize(new java.awt.Dimension(117, 64));
    lectures.add(jLabel7);

    settings.setBackground(closedColor);
    settings.setMaximumSize(new java.awt.Dimension(235, 64));
    settings.setMinimumSize(new java.awt.Dimension(235, 64));
    settings.setPreferredSize(new java.awt.Dimension(235, 64));
    settings.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        settingsMouseClicked(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 28)); // NOI18N
    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("Settings");
    jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    settings.add(jLabel8);

    javax.swing.GroupLayout sideItemsLayout = new javax.swing.GroupLayout(sideItems);
    sideItems.setLayout(sideItemsLayout);
    sideItemsLayout.setHorizontalGroup(
      sideItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lectures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(sections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(assignments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    sideItemsLayout.setVerticalGroup(
      sideItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(sideItemsLayout.createSequentialGroup()
        .addComponent(lectures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(assignments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 160, 0);
    sideBar.add(sideItems, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.ipadx = 240;
    gridBagConstraints.ipady = 180;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    sideBar.add(filler2, gridBagConstraints);
    sideBar.add(filler1, new java.awt.GridBagConstraints());

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(57, 57, 57)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1401, Short.MAX_VALUE)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  
  boolean lectureOpen = true;
  boolean sectionOpen = false;
  boolean assignmentOpen = false;
  boolean settingsOpen = false;
  
  private void changeBackgroundColor(String name) {
    regularBackground();
    switch (name) {
      case "lectures":
        lectures.setBackground(openedColor);
        lectureOpen = true;
      break;
      case "sections":
        sections.setBackground(openedColor);
        sectionOpen = true;
      break;
      case "assignments":
        assignments.setBackground(openedColor);
        assignmentOpen = true;
      break;
      default:
        settings.setBackground(openedColor);
        settingsOpen = true;
    }
    revalidate();
    repaint();
  }
  private void regularBackground() {
    lectureOpen = false;
    sectionOpen = false;
    assignmentOpen = false;
    settingsOpen = false;
    lectures.setBackground(closedColor);
    sections.setBackground(closedColor);
    assignments.setBackground(closedColor);
    settings.setBackground(closedColor);
  }
  
  private void assignmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentsMouseClicked
    if (evt.getButton() == 1) {
      changeBackgroundColor("assignments");
      evt.consume();
    }
  }//GEN-LAST:event_assignmentsMouseClicked

  private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
    if (evt.getButton() == 1) {
      changeBackgroundColor("settings");
      evt.consume();
    }
  }//GEN-LAST:event_settingsMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel assignments;
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.JPanel header;
  private javax.swing.JFrame jFrame1;
  private javax.swing.JFrame jFrame2;
  private javax.swing.JFrame jFrame3;
  private javax.swing.JFrame jFrame4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel lectures;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JPanel sections;
  private javax.swing.JLabel semester;
  private javax.swing.JPanel settings;
  private javax.swing.JPanel sideBar;
  private javax.swing.JPanel sideItems;
  private javax.swing.JPanel studentGrade;
  private javax.swing.JLabel studentName;
  private javax.swing.JLabel title;
  private javax.swing.JLabel year;
  // End of variables declaration//GEN-END:variables
}
