/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.amr0khaled.student_organizer.panes;
import com.amr0khaled.student_organizer.custom_ui.Colors;

/**
 *
 * @author rami3
 */
public class HomePanel extends javax.swing.JPanel {

  /**
   * Creates new form HomePanel
   */
  public HomePanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setBackground(Colors.background);
    setForeground(Colors.text);
    setFocusable(false);
    setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    setMaximumSize(new java.awt.Dimension(1920, 1080));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setName("Home"); // NOI18N
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setLayout(new java.awt.BorderLayout());

    jPanel1.setBackground(Colors.background);
    jPanel1.setForeground(Colors.text);
    jPanel1.setMaximumSize(new java.awt.Dimension(1920, 96));
    jPanel1.setMinimumSize(new java.awt.Dimension(1280, 96));
    jPanel1.setPreferredSize(new java.awt.Dimension(1280, 96));
    jPanel1.setRequestFocusEnabled(false);

    jPanel2.setBackground(Colors.background);
    jPanel2.setForeground(Colors.text);
    jPanel2.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    jPanel2.setMaximumSize(new java.awt.Dimension(1920, 96));
    jPanel2.setMinimumSize(new java.awt.Dimension(1280, 96));
    jPanel2.setPreferredSize(new java.awt.Dimension(1280, 96));

    jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
    jLabel1.setText("Student Material Organizer");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jLabel1)
        .addContainerGap(935, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addComponent(jLabel1)
        .addContainerGap(30, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(624, Short.MAX_VALUE))
    );

    add(jPanel1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
