/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.amr0khaled.student_organizer.panes;
import com.amr0khaled.student_organizer.custom_ui.Colors;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.Objects;
import javax.swing.JOptionPane;
/**
 *
 * @author rami3
 */
public class LoginPanel extends javax.swing.JPanel {

  /**
   * Creates new form LoginPanel
   */
  private String AUTHED = "Auth";
  private boolean authed = false;
  private PropertyChangeSupport pcs;
  public LoginPanel() {
    pcs = new PropertyChangeSupport(this);
    setAuthed(false);
    initComponents();
  }
  public void addPropertyChangeListener(PropertyChangeListener listener) {
     pcs.addPropertyChangeListener(listener);
   }

   public void removePropertyChangeListener(PropertyChangeListener listener) {
     pcs.removePropertyChangeListener(listener);
   }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLayeredPane2 = new javax.swing.JLayeredPane();
    loginLabel = new javax.swing.JLabel();
    jLayeredPane1 = new javax.swing.JLayeredPane();
    passwordPanel = new javax.swing.JLayeredPane();
    passwordLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JPasswordField();
    getMeIn = new javax.swing.JButton();
    usernamePanel = new javax.swing.JLayeredPane();
    usernameLabel = new javax.swing.JLabel();
    usernameField = new javax.swing.JTextField();

    setBackground(Colors.background);
    setForeground(Colors.text);
    setMaximumSize(new java.awt.Dimension(1920, 1080));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setLayout(new javax.swing.OverlayLayout(this));

    loginLabel.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
    loginLabel.setForeground(Colors.text);
    loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginLabel.setText("Log In");
    loginLabel.setToolTipText("");
    loginLabel.setFocusable(false);

    passwordLabel.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
    passwordLabel.setForeground(Colors.text);
    passwordLabel.setText("Password");

    passwordField.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    passwordField.setToolTipText("Type your password");
    passwordField.setMaximumSize(new java.awt.Dimension(677, 64));
    passwordField.setMinimumSize(new java.awt.Dimension(508, 48));
    passwordField.setPreferredSize(new java.awt.Dimension(508, 48));

    passwordPanel.setLayer(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    passwordPanel.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
    passwordPanel.setLayout(passwordPanelLayout);
    passwordPanelLayout.setHorizontalGroup(
      passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(passwordPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(passwordPanelLayout.createSequentialGroup()
            .addComponent(passwordLabel)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    passwordPanelLayout.setVerticalGroup(
      passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(passwordPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(passwordLabel)
        .addGap(8, 8, 8)
        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    getMeIn.setBackground(Colors.primary);
    getMeIn.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
    getMeIn.setForeground(Colors.text);
    getMeIn.setText("Get me in");
    getMeIn.setToolTipText("Press to get you in");
    getMeIn.setMaximumSize(new java.awt.Dimension(677, 72));
    getMeIn.setMinimumSize(new java.awt.Dimension(508, 64));
    getMeIn.setName(""); // NOI18N
    getMeIn.setPreferredSize(new java.awt.Dimension(508, 64));
    getMeIn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        getMeInMouseClicked(evt);
      }
    });

    usernameLabel.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
    usernameLabel.setForeground(Colors.text);
    usernameLabel.setText("User Name");

    usernameField.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    usernameField.setToolTipText("Type your user name");
    usernameField.setMaximumSize(new java.awt.Dimension(677, 64));
    usernameField.setMinimumSize(new java.awt.Dimension(508, 48));
    usernameField.setPreferredSize(new java.awt.Dimension(508, 48));

    usernamePanel.setLayer(usernameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    usernamePanel.setLayer(usernameField, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
    usernamePanel.setLayout(usernamePanelLayout);
    usernamePanelLayout.setHorizontalGroup(
      usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(usernamePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(usernameLabel)
          .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    usernamePanelLayout.setVerticalGroup(
      usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(usernamePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(usernameLabel)
        .addGap(8, 8, 8)
        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jLayeredPane1.setLayer(passwordPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(getMeIn, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(usernamePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addGap(8, 8, 8)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(getMeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    jLayeredPane1Layout.setVerticalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(16, 16, 16)
        .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(16, 16, 16)
        .addComponent(getMeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jLayeredPane2.setLayer(loginLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
    jLayeredPane2.setLayout(jLayeredPane2Layout);
    jLayeredPane2Layout.setHorizontalGroup(
      jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(loginLabel))
        .addContainerGap())
    );

    jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLayeredPane1, loginLabel});

    jLayeredPane2Layout.setVerticalGroup(
      jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(loginLabel)
        .addGap(32, 32, 32)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    add(jLayeredPane2);
  }// </editor-fold>//GEN-END:initComponents

  private boolean checkChar(int c) {
    if (
        (c >= 33 && c < 127)
      ) {
      return true;
    }
      return false;
  }
  private void getMeInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getMeInMouseClicked
    if (!usernameField.getText().isEmpty() && passwordField.getPassword().length != 0) {
      String username = usernameField.getText();
      char[] passwordchrs = passwordField.getPassword();
      String password = String.valueOf(passwordchrs);
      if (Objects.equals(username, "Amr") && Objects.equals(password, "12345")) {
        setAuthed(true);
      } else {
        JOptionPane.showMessageDialog(this, "Username or Password is incorrect", "Login Error", JOptionPane.ERROR_MESSAGE);
      }
    }
  }//GEN-LAST:event_getMeInMouseClicked
  public void setAuthed(boolean value) {
    boolean old = authed;
    authed = value;
    if (authed != old) {
      pcs.firePropertyChange(AUTHED, old, value);
    }
  }
  public boolean getAuthed() {
    return authed;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton getMeIn;
  private javax.swing.JLayeredPane jLayeredPane1;
  private javax.swing.JLayeredPane jLayeredPane2;
  private javax.swing.JLabel loginLabel;
  private javax.swing.JPasswordField passwordField;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JLayeredPane passwordPanel;
  private javax.swing.JTextField usernameField;
  private javax.swing.JLabel usernameLabel;
  private javax.swing.JLayeredPane usernamePanel;
  // End of variables declaration//GEN-END:variables
}
