/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amr0khaled.student_organizer;
import com.amr0khaled.student_organizer.controller.LoginController;
import com.amr0khaled.student_organizer.controller.SubjectController;
import com.amr0khaled.student_organizer.custom_ui.Colors;
import com.amr0khaled.student_organizer.panes.DashboardPanel;
import com.amr0khaled.student_organizer.panes.LoginPanel;


import javax.swing.JPanel;
/**
 *
 * @author rami3
 */
public class Framer extends javax.swing.JFrame {
  private LoginPanel login;
  private DashboardPanel dashboard;
  private JPanel card;
  /**
   * Creates new form Framer
   */
  public Framer(LoginController auth) {
    initComponents();
    card = (JPanel) getContentPane();
    init(auth);
    showLogin();
  }
  private String LOGIN_PANE = "login page";
  private String DASHBOARD_PANE = "dashboard page";
  
  private void init(LoginController auth) {
    login = new LoginPanel();
    login.setVisible(false);
    card.add(LOGIN_PANE, login);
    
    dashboard = DashboardPanel.getInstance();
    dashboard.setPath(SubjectController.getInstance().location);
    dashboard.refresh();
    dashboard.setVisible(false);
    card.add(DASHBOARD_PANE, dashboard);
  }
  private void showLogin() {
    login.setVisible(true);
    login.addPropertyChangeListener(e -> {
     if ("Auth".equals(e.getPropertyName()) && (boolean)login.getAuthed()) {
       login.setVisible(false);
       showDashboard();
     }
    });
  }
  private void showDashboard() {
     dashboard.setVisible(true);
     card.revalidate();
     card.repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Student Material Origanizer");
    setBackground(Colors.background);
    setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    setForeground(Colors.text);
    setMaximumSize(new java.awt.Dimension(1920, 1080));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setSize(new java.awt.Dimension(1280, 720));
    getContentPane().setLayout(new java.awt.CardLayout());

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
